---
version: '3.8'
services:

  prometheus:
    image: "prom/prometheus:v2.22.1" # https://hub.docker.com/r/prom/prometheus

    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: bind
        source: ./alerts.yml
        target: /etc/prometheus/alerts.yml
    depends_on:
      - alertmanager

  alertmanager:
    image: "prom/alertmanager:v0.21.0"

    ports:
      - "9093:9093"
    volumes:
      - type: bind
        source: ./alertmanager.yml
        target: /etc/alertmanager/alertmanager.yml

  grafana:
    image: "grafana/grafana:7.3.2"

    ports:
      - "3000:3000"
