---
version: '3.8'
services:

  prometheus:
    image: "prom/prometheus:v2.22.1" # https://hub.docker.com/r/prom/prometheus

    # ports:
    #   - "9090:9090"
    network_mode: "host"
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /opt/app/static

  grafana:
    image: "grafana/grafana:7.3.2"

    # ports:
    #   - "3000:3000"
    network_mode: "host"
