global:
  scrape_interval: 10s

# A list of scrape configurations.
scrape_configs:
  - job_name: xblagues
    static_configs:
      - targets:
          - 'localhost:5000'
        labels:
          source: "xblagues"
