global:
  scrape_interval:      10s   # How frequently to scrape targets
  evaluation_interval:  10s   # How frequently to evaluate rules (alerts)

# A list of scrape configurations.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:9090'
  - job_name: xblagues
    static_configs:
      - targets:
          - 'host.docker.internal:5000'
        labels:
          source: "xblagues"

rule_files:
  - alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            # Alertmanager's default port is 9093
            - 'host.docker.internal:9093'
